### ISSUE TITLE
Final QA/Bug fixes are complete

### ISSUE THREAD

**Issue by ACParker89** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#93] opened 2024-08-20 17:28 UTC
User story
As an engineer I would like to complete the final set of bug fixes and QA updates prior to our research sessions.
 
- Minor bugs or fixes should be addressed around quirks found in staging
  - Updating the phone in task purple does not work in staging. Since we are clearing out the field when the phone is edited, this creates the wrong method for the api call (a POST instead of a PUT) and that results in the api rejecting the update on the BE. It works fine in local / codespaces since the api is mocked.
  
- Extra: Updating the address in staging also seems to have issues, in that it hangs or doesn't return to the previous page at times ( since this is only present in staging, and seems to be intermitent, we can continue to look at this if needed)

- QA items should be addressed

Acceptance Criteria

- [x] PR for fixed has been merged for purple task
- [x] Items from the [QA google doc](https://docs.google.com/document/d/1xOraL1E992HkkoZruDFdd5b3j6zy4M1Ixw00BGzddmc/edit#heading=h.eppxqknnfj5k) have been addressed and PR has been merged
- [x] Work has been reviewed by team and confirmed as functioning on [Codespaces](https://musical-doodle-7676579pxr3rxrg-3001.app.github.dev/mock-form-ae-design-patterns/) as expected
- [x] Adam's [final PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31645) approved to fix content in prefill alert & add scroll to top

**Comment by ACParker89** [comment] 2024-08-20 17:29
@adamwhitlock1 @msbtterswrth - refine/task/etc prior to sprint 6 please!

**Comment by ChristineRoseSteiffer** [comment] 2024-08-26 15:27
Here is the list of issues from the QA - https://docs.google.com/document/d/1xOraL1E992HkkoZruDFdd5b3j6zy4M1Ixw00BGzddmc/edit#heading=h.eppxqknnfj5k

**Comment by adamwhitlock1** [comment] 2024-08-26 23:10
@bellepx0 and I worked through all the QA items today and each put in PRs to address the items. The changes are now merged into main and are live on the musical doodle codespace.

A couple notes:

- Breadcrumbs may be something that we can set up, but would not look like the breadcrumbs in the designs, due to this application not living in the same nested link structure that is used on forms like the 1010ezr. We can look into adding those, but I think that a change first has to be submitted on the `content-build` repository, as each entry into the registry file has a property: ` "includeBreadcrumbs": true,` that we would need to add to our app's entry.
- In regards to the potential bug around the autosave. That is part of the form system right now, and we are mocking the successful auto-save, but we aren't changing anything about how that alert appears, so that is something that can't be removed from that page at this time.

@beckyphung and @msbtterswrth We can review this work now though, and I have spun up the codespace to be live for the next 4ish hours and will make a point to have it up and live first thing in the morning as well so that it can be viewed throughout the day.

**Comment by msbtterswrth** [comment] 2024-08-27 15:50
Just reviewed everything and we're looking good! going to mark as reviewed and send it to Becky :)

**Comment by beckyphung** [comment] 2024-08-27 19:32
Thanks for getting these fixes in. See my QA notes below. 

@msbtterswrth and/or @ChristineRoseSteiffer Could you review the below and let me know what you think about the prioritization?

### Things that will probably need to get updated before research
Yellow
- Prefill alert text is incorrect on the `Mailing address` page with the gray card. Instead of "...you can edit the form fields below." it should be "...you can select edit below."

### Things that probably won't block research
**All tasks**
- We're using both the word `application`, `form`, and `request` to refer to the form. Which one should we be using? Example: Finish this **form** later OR Finish this **application** later

**Green & Yellow tasks**
- Feedback button missing from 'Need help' section

**Yellow tasks**
- Missing auto-save alert on pages

**Comment by ChristineRoseSteiffer** [comment] 2024-08-27 20:39
Its an interesting conversation about 'application' 'form' and 'request'. I think each form is supposed to clarify which one should be used on a case by case basis. For instance, 10182 does use 'request' - maybe because the purpose is to request a board appeal? Whereas the language around application vs form seems interchangeable but not used consistently everywhere else. I see both in staging for the 1010ezr. CAIA had recommended that we use 'application' since that was in the 'Need Help' section, but I dont know if they noticed the 'Finish this form later' when they made that suggestion. I can take the question back to them for follow up and to see if there is general guidance on when to use which one. 

I agree with your first comment of updating the text in the prefill alert, as well as the feedback button needing to get added back in at the bottom of the 'Need Help' section. 

I wasn't able to recreate the auto-save alert not posting on the Yellow task. I've attached a screenshot showing it at the bottom of the Address Display page after I clicked on the 'Yes' radio button. Is it behaving differently for you @beckyphung or @adamwhitlock1 ?


![Image](https://github.com/user-attachments/assets/e59f5f66-fba3-42b7-af76-a0c48f9f6f0f)

**Comment by adamwhitlock1** [comment] 2024-08-28 15:10
The autosave alert only shows on that page with the radio button for "Is your home address the same as you mailing address?" and displays after you click on a selection and focus off of it, since that is how the listener is set up in the form system.

So as far as I can tell, that is functioning as expected. It doesn't show on the editing page for mailing address since that one actually requires the user to click save in order to actually save the info. Hope that clears things up.

Also I have submitted a PR for the content updates on the alert for task Yellow, along with the scroll to top that was requested for the editing of mailing address page on Task Green. https://github.com/department-of-veterans-affairs/vets-website/pull/31645

I'll keep yall posted on that getting merged to main, but it is live in the codespace right now for review.

**Comment by beckyphung** [comment] 2024-08-28 15:11
> I can take the question back to them for follow up and to see if there is general guidance on when to use which one.
Yes let's check with CAIA about this!

> So as far as I can tell, that is functioning as expected
Yes confirmed too! Thanks for sharing the screenshot/steps @ChristineRoseSteiffer and @adamwhitlock1. I just checked too.

**Comment by adamwhitlock1** [comment] 2024-08-28 15:14
Also, do we think the feedback button is needed? 

I can add it, but it wont be functional as I _think_ that ties to the third party feedback tool medalia.

**Comment by beckyphung** [comment] 2024-08-28 15:17
IMO, I don't think it's needed for our research purposes. The only con is then our prototype doesn't mirror VA.gov. We could just add it in the next test, and leave it off of this one. @ChristineRoseSteiffer / @msbtterswrth ?

**Comment by msbtterswrth** [comment] 2024-08-28 18:14
Sounds good to me!!

**Comment by beckyphung** [comment] 2024-08-28 18:23
Adam's PR was approved. I see the changes in staging too. @msbtterswrth I know you mentioned in Slack adding this work actually to #98 or #95. Do you want me to remove the AC related to this last update, so I can accept the story for the previous sprint, Sprint 5? 

Or do you want to keep this AC in this issue? In which case, the sprint needs to be updated to Spring 6 for this issue.

**Comment by msbtterswrth** [comment] 2024-08-28 19:14
Let's keep it accurate and push this into 6!

**Comment by beckyphung** [comment] 2024-08-28 20:00
Thanks for moving into 6. Moving this to closed.

**Closed by beckyphung** 2024-08-28 20:00 UTC
Labels: engineering, [Pattern] Know when their information is prefilled
